### PR TITLE
Update for node 12

### PR DESCRIPTION
**Pull request by sebakerckhof**

### CODE REVIEW

**Comment by sebakerckhof** [comment]
ping @veered

**Comment by gregory** [comment]
@veered any update on this? is this project still active?

**Comment by adamantivm** [comment]
ping, we're also interested in this. Any chance to get it released any time soon?

**Comment by veered** [comment]
Thanks @sebakerckhof!

I'll merge and publish. It'll have to be a major version bump since this is backwards incompatible with all Meteor versions older than 1.8.2.

**Pull request merged**
